# Generated by Django 4.1.4 on 2022-12-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(blank=True, max_length=100, null=True)),
                ('CDesc', models.CharField(blank=True, max_length=100, null=True)),
                ('CImage', models.ImageField(blank=True, null=True, upload_to='student')),
            ],
        ),
    ]
